# Generated by Django 6.1.2 on 2026-10-07 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_percurso', models.DecimalField(decimal_places=2, help_text='Valor cobrado por trecho único', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('IDA', 'Apenas ida'), ('VOLTA', 'Apenas volta'), ('IDA_VOLTA', 'Ida e Volta')], max_length=15)),
                ('valor_total', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('pago', models.BooleanField(default=False)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to='caronas.passageiro')),
            ],
        ),
    ]
